server:
  port: 9000
  
eureka:                  
  client:
   serviceUrl:
    defaultZone: http://localhost:8761/eureka
    
        # MYSQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://supercomputacion.cng9pov0wudy.us-east-1.rds.amazonaws.com:3306/empleosbd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: ramonsqlvalladolid
     
     # JPA
  jpa:
    generate-ddl: false
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQLDialect
        naming: 
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true



      
